// auth
export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESSFUL';
export const AUTH_USER_RESET = 'AUTH_USER_RESET';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

// offers
export const OFFER_FETCH_ALL_SUCCESS = 'OFFER_FETCH_ALL_SUCCESS';
export const OFFER_FETCH_ONE_SUCCESS = 'OFFER_FETCH_ONE_SUCCESS';
export const OFFER_FETCH_MINE_SUCCESS = 'OFFER_FETCH_MINE_SUCCESS';
export const OFFER_REMOVE_SUCCESS = 'OFFER_REMOVE_SUCCESS';
export const OFFER_UPDATE_SUCCESS = 'OFFER_UPDATE_SUCCESS';
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS';

// card
export const CARD_ADD_OFFER_SUCCESS = 'CARD_ADD_OFFER_SUCCESS';
export const CARD_REMOVE_OFFER_SUCCESS = 'CARD_REMOVE_OFFER_SUCCESS';

// reservation
export const RESERVATION_CREATE_SUCCESS = 'RESERVATION_CREATE_SUCCESS';
export const RESERVATION_FETCH_BOUGHT_SUCCESS = 'RESERVATION_FETCH_BOUGHT_SUCCESS';
export const RESERVATION_FETCH_SOLD_SUCCESS = 'RESERVATION_FETCH_SOLD_SUCCESS';
export const RESERVATION_SELECT_SUCCESS = 'RESERVATION_SELECT_SUCCESS';

// reservation lines
export const RESERVATION_LINES_FETCH_SUCCESS = 'RESERVATION_LINES_FETCH_SUCCESS';
export const RESERVATION_LINES_CHANGE_STATUS_SUCCESS = 'RESERVATION_LINES_CHANGE_STATUS_SUCCESS';

// loading
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

// error
export const ERROR = 'ERROR';
