// auth
export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESSFUL';
export const AUTH_USER_RESET = 'AUTH_USER_RESET';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

// offers
export const OFFER_FETCH_ALL_SUCCESS = 'OFFER_FETCH_ALL_SUCCESS';
export const OFFER_FETCH_ONE_SUCCESS = 'OFFER_FETCH_ONE_SUCCESS';
export const OFFER_FETCH_MINE_SUCCESS = 'OFFER_FETCH_MINE_SUCCESS';
export const OFFER_REMOVE_SUCCESS = 'OFFER_REMOVE_SUCCESS';
export const OFFER_UPDATE_SUCCESS = 'OFFER_UPDATE_SUCCESS';
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS';

// card
export const ADD_OFFER_TO_CARD = 'ADD_OFFER_TO_CARD';
export const REMOVE_OFFER_FROM_CARD = 'REMOVE_OFFER_FROM_CARD';

// loading
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
